# Generated by Django 3.0.4 on 2020-03-24 06:19

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BD',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('author', models.CharField(blank=True, max_length=50)),
                ('date_posted', models.DateTimeField(default=datetime.datetime(2020, 3, 24, 6, 19, 8, 261453, tzinfo=utc))),
            ],
        ),
    ]
